"""What a test double pretended to send, so a developer can read it.

A fake provider that returns a reference and throws the message away makes
`mobile_otp` untestable: the code exists, it is valid for five minutes, and
nothing anywhere can tell you what it is. This is the smallest thing that
fixes that.

**Redis-backed, bounded, and TTL'd.** The deployment this runs under is
gunicorn with several worker processes; a send lands in whichever worker
handled the request, and a read is served by whichever worker the load
balancer picks next. A module-level `deque` cannot bridge that — it is
process-local no matter how carefully it is locked — which measured against
the running stack as 2 of 12 outbox reads returning a message after one OTP
send, and 10 returning nothing. So the store has to live somewhere every
worker can reach, and Redis is that somewhere: it is already a live
dependency here (`core/cache.py`, the rate limiter, `otp_throttle.py`), so
this reuses `core.cache.redis_client()` rather than opening a second
connection pool or inventing a second way to find `REDIS_URL`. `LTRIM` keeps
it bounded at `CAPACITY` and `EXPIRE` gives it a TTL, so this is still the
same ring buffer the docstring below always promised — a table would still
mean a migration and a purge job neither of which this needs — just backed by
a store all workers share instead of one only.

**Why plaintext in Redis is not the argument that ruled out a database
table.** The reasoning that kept this out of Postgres was about durability,
not about memory versus disk: a table survives a migration, gets backed up,
and needs a purge job to ever stop holding a code. None of that is true here.
Every entry expires on its own (`_TTL_SECONDS`), the key is never part of a
backup or a restore, and — the part that actually matters — everything this
ever holds was generated by a test double that cannot reach a real phone. A
leaked entry here is a fictional code for a conversation that never happened,
not a live secret. The property this module has always needed is "gone soon,
reachable by no one outside a dev session," and Redis with a TTL gives that
as fully as an in-process deque did.

**Falls back to the in-memory deque when Redis is not reachable.** No
`REDIS_URL` (the test suite, a bare local run) or Redis being down must
behave exactly as this module always has — silently and without raising, the
same fail-open posture `core/cache.py` takes, not the fail-closed one
`otp_throttle.py` takes for money-spending limits. Losing the outbox costs a
developer a dev-tool convenience; failing loudly here would cost nothing and
break the thing this module exists to keep out of the way of.

**Not reachable in production.** The endpoint that reads this consults
`resolver._test_doubles_allowed`, the same predicate that decides whether a
fake may run at all. One predicate rather than two that can disagree.
"""

from __future__ import annotations

import json
import logging
import threading
from collections import deque
from typing import Dict, List, Optional

from core.school_time import utc_now

logger = logging.getLogger(__name__)

#: How many messages to keep — in Redis (via `LTRIM`) and in the in-memory
#: fallback alike. Enough to debug a flow, few enough that neither store can
#: grow into a memory problem in a long-running development server.
CAPACITY = 50

#: Own namespace, distinct from `core/cache.py`'s `erp:cache:v1` prefix so a
#: bulk cache invalidation (`delete_pattern`) can never sweep this away.
_REDIS_KEY = "erp:outbox:v1:messages"

#: Refreshed on every write. Long enough to outlast a developer reading one
#: OTP out of the panel; short enough that a forgotten dev session does not
#: leave fictional messages sitting in Redis indefinitely.
_TTL_SECONDS = 3600

_messages: deque = deque(maxlen=CAPACITY)
_lock = threading.Lock()


def _redis():
    """The shared Redis client `core/cache.py` already maintains, or `None`.

    Imported inside the function, not at module scope, so a test that
    monkeypatches `core.cache.redis_client` (to simulate "no Redis" or "Redis
    is down") is seen on the next call rather than bound once at import time.
    """
    from core.cache import redis_client

    return redis_client()


def _record_to_redis(entry: Dict) -> bool:
    """Push, trim to `CAPACITY`, and refresh the TTL — atomically. `True` on
    success, `False` if Redis is unavailable or the write failed, either of
    which means the caller should use the in-memory fallback instead."""
    client = _redis()
    if client is None:
        return False
    try:
        payload = json.dumps(entry, separators=(",", ":"))
        pipe = client.pipeline()
        pipe.lpush(_REDIS_KEY, payload)
        pipe.ltrim(_REDIS_KEY, 0, CAPACITY - 1)
        pipe.expire(_REDIS_KEY, _TTL_SECONDS)
        pipe.execute()
        return True
    except Exception:
        logger.debug("outbox: redis write failed, using in-memory fallback", exc_info=True)
        return False


def _recent_from_redis(limit: int) -> Optional[List[Dict]]:
    """The most recent messages from Redis, or `None` if Redis could not be
    read — `None` rather than `[]` so the caller can tell "unreachable" apart
    from "genuinely empty" and fall back only for the former."""
    client = _redis()
    if client is None:
        return None
    try:
        raw = client.lrange(_REDIS_KEY, 0, max(0, limit - 1))
    except Exception:
        logger.debug("outbox: redis read failed, using in-memory fallback", exc_info=True)
        return None
    return [json.loads(item) for item in raw]


def record(*, tenant_id: str, channel: str, destination: str, body: str, purpose: str) -> None:
    """Keep what a fake provider was asked to send.

    Called only from `messaging.send_message`, after a test double reports
    success. A real provider must never reach this: the body of a real OTP is
    a live secret, and the whole argument for keeping this in a dev-only store
    rests on it only ever holding fictional ones.
    """
    entry = {
        "tenant_id": tenant_id,
        "channel": channel,
        "destination": destination,
        "body": body,
        "purpose": purpose,
        "sent_at": utc_now().isoformat(),
    }
    if _record_to_redis(entry):
        return
    with _lock:
        _messages.appendleft(entry)


def recent(limit: int = 20) -> List[Dict]:
    """The most recent messages, newest first."""
    messages = _recent_from_redis(limit)
    if messages is not None:
        return messages
    with _lock:
        return list(_messages)[: max(1, limit)]


def clear() -> None:
    """Empty it. For tests, and for a developer starting a fresh walk-through.

    Clears both stores unconditionally rather than only whichever one is
    "current" — there is no single source of truth to ask, since Redis
    availability can change between calls, and a stale entry left behind in
    whichever store was not just used would resurface the moment that store
    became the active one again.
    """
    client = _redis()
    if client is not None:
        try:
            client.delete(_REDIS_KEY)
        except Exception:
            logger.debug("outbox: redis clear failed", exc_info=True)
    with _lock:
        _messages.clear()
