"""school_setup_redesign_phase1

Adds the columns, tables, indexes, and CHECK constraints needed for the
school setup redesign (Tasks 1 and 2).

Scope:
  - school_units.gr_number_scheme           (new column)
  - classes.stream                          (new column + index + CHECK)
  - tenants.offboarding_started_at          (new column)
  - tenants.purge_scheduled_at              (new column)
  - tenants.setup_template_used             (new column + CHECK)
  - users.default_unit_id                   (new column + index + FK)
  - tenant_audit_logs                       (new table + indexes)
  - setup_module_events                     (new table + indexes)
  - data_purge_logs                         (new table + indexes)
  - subject_template_groups                 (new table + indexes)
  - subject_template_items                  (new table + indexes)

The autogenerated diff also produced a large amount of unrelated drift
(index renames, JSONB->JSON downgrades, dropped partial unique
constraints, etc.) caused by historical mismatches between the live
schema and current model declarations. None of that drift is part of
the school setup redesign and is intentionally NOT included here so
this migration stays focused, reviewable, and reversible.

Revision ID: 6ef586ca739c
Revises: 053_setup_telemetry_and_medium_unique
Create Date: 2026-05-06 02:03:55.530163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ef586ca739c"
down_revision = "053_setup_telemetry_and_medium_unique"
branch_labels = None
depends_on = None


def upgrade():
    # ---- New columns on existing tables ----------------------------------

    op.add_column(
        "school_units",
        sa.Column(
            "gr_number_scheme",
            sa.String(length=64),
            nullable=True,
            comment=(
                "GR number format, e.g. 'MN-{SEQ}'. {SEQ} is replaced with "
                "zero-padded auto-increment per unit."
            ),
        ),
    )

    op.add_column(
        "classes",
        sa.Column(
            "stream",
            sa.String(length=32),
            nullable=True,
            comment=(
                "Grade 11-12 stream: Science, Commerce, Arts, Vocational. "
                "NULL for Grade 1-10."
            ),
        ),
    )
    op.create_index("ix_classes_stream", "classes", ["stream"], unique=False)
    op.create_check_constraint(
        "ck_classes_stream",
        "classes",
        "stream IS NULL OR stream IN ('Science', 'Commerce', 'Arts', 'Vocational')",
    )

    op.add_column(
        "tenants",
        sa.Column("offboarding_started_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "tenants",
        sa.Column("purge_scheduled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "setup_template_used",
            sa.String(length=50),
            nullable=True,
            comment=(
                "board_code of template used at setup: cbse, icse, "
                "gujarat_state_board, ib, custom"
            ),
        ),
    )
    op.create_check_constraint(
        "ck_tenants_setup_template_used",
        "tenants",
        "setup_template_used IS NULL OR setup_template_used IN "
        "('cbse', 'icse', 'gujarat_state_board', 'ib', 'custom')",
    )

    op.add_column(
        "users",
        sa.Column(
            "default_unit_id",
            sa.String(length=36),
            nullable=True,
            comment=(
                "Preferred campus for this admin. NULL = show all units. "
                "UI filter only, not a permission gate."
            ),
        ),
    )
    op.create_index(
        "ix_users_default_unit_id", "users", ["default_unit_id"], unique=False
    )
    op.create_foreign_key(
        "fk_users_default_unit_id",
        "users",
        "school_units",
        ["default_unit_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # ---- New tables ------------------------------------------------------

    op.create_table(
        "tenant_audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("unit_id", sa.String(length=36), nullable=True),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("actor_name", sa.Text(), nullable=False),
        sa.Column("actor_role", sa.String(length=50), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["school_units.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tenant_audit_logs_actor_user_id",
        "tenant_audit_logs",
        ["actor_user_id"],
    )
    op.create_index(
        "ix_tenant_audit_logs_created_at", "tenant_audit_logs", ["created_at"]
    )
    op.create_index(
        "ix_tenant_audit_logs_module", "tenant_audit_logs", ["module"]
    )
    op.create_index(
        "ix_tenant_audit_logs_tenant_id", "tenant_audit_logs", ["tenant_id"]
    )
    op.create_index(
        "ix_tenant_audit_logs_unit_id", "tenant_audit_logs", ["unit_id"]
    )
    # Multi-column query indexes (autogenerate does not infer these).
    op.create_index(
        "idx_tenant_audit_logs_tenant_created",
        "tenant_audit_logs",
        ["tenant_id", "created_at"],
    )
    op.create_index(
        "idx_tenant_audit_logs_module",
        "tenant_audit_logs",
        ["tenant_id", "module", "created_at"],
    )

    op.create_table(
        "setup_module_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("event", sa.String(length=50), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_setup_module_events_actor_user_id",
        "setup_module_events",
        ["actor_user_id"],
    )
    op.create_index(
        "ix_setup_module_events_created_at",
        "setup_module_events",
        ["created_at"],
    )
    op.create_index(
        "ix_setup_module_events_tenant_id",
        "setup_module_events",
        ["tenant_id"],
    )

    op.create_table(
        "data_purge_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("data_type", sa.String(length=50), nullable=False),
        sa.Column("records_deleted", sa.Integer(), nullable=False),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_data_purge_logs_tenant_id", "data_purge_logs", ["tenant_id"]
    )

    op.create_table(
        "subject_template_groups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("board_code", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_subject_template_groups_board_code",
        "subject_template_groups",
        ["board_code"],
        unique=True,
    )

    op.create_table(
        "subject_template_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("template_group_id", sa.String(length=36), nullable=False),
        sa.Column("grade_number", sa.Integer(), nullable=False),
        sa.Column(
            "stream",
            sa.String(length=32),
            nullable=True,
            comment=(
                "NULL = all streams (Grade 1-10). "
                "Science/Commerce/Arts/Vocational for Grade 11-12."
            ),
        ),
        sa.Column("subject_name", sa.String(length=100), nullable=False),
        sa.Column("subject_code", sa.String(length=20), nullable=True),
        sa.Column("periods_per_week", sa.Integer(), nullable=True),
        sa.Column("is_elective", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_group_id"],
            ["subject_template_groups.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_subject_template_items_template_group_id",
        "subject_template_items",
        ["template_group_id"],
    )


def downgrade():
    # ---- New tables ------------------------------------------------------

    op.drop_index(
        "ix_subject_template_items_template_group_id",
        table_name="subject_template_items",
    )
    op.drop_table("subject_template_items")

    op.drop_index(
        "ix_subject_template_groups_board_code",
        table_name="subject_template_groups",
    )
    op.drop_table("subject_template_groups")

    op.drop_index("ix_data_purge_logs_tenant_id", table_name="data_purge_logs")
    op.drop_table("data_purge_logs")

    op.drop_index(
        "ix_setup_module_events_tenant_id", table_name="setup_module_events"
    )
    op.drop_index(
        "ix_setup_module_events_created_at", table_name="setup_module_events"
    )
    op.drop_index(
        "ix_setup_module_events_actor_user_id", table_name="setup_module_events"
    )
    op.drop_table("setup_module_events")

    op.drop_index("idx_tenant_audit_logs_module", table_name="tenant_audit_logs")
    op.drop_index(
        "idx_tenant_audit_logs_tenant_created", table_name="tenant_audit_logs"
    )
    op.drop_index("ix_tenant_audit_logs_unit_id", table_name="tenant_audit_logs")
    op.drop_index("ix_tenant_audit_logs_tenant_id", table_name="tenant_audit_logs")
    op.drop_index("ix_tenant_audit_logs_module", table_name="tenant_audit_logs")
    op.drop_index("ix_tenant_audit_logs_created_at", table_name="tenant_audit_logs")
    op.drop_index(
        "ix_tenant_audit_logs_actor_user_id", table_name="tenant_audit_logs"
    )
    op.drop_table("tenant_audit_logs")

    # ---- Columns on existing tables --------------------------------------

    op.drop_constraint("fk_users_default_unit_id", "users", type_="foreignkey")
    op.drop_index("ix_users_default_unit_id", table_name="users")
    op.drop_column("users", "default_unit_id")

    op.drop_constraint("ck_tenants_setup_template_used", "tenants", type_="check")
    op.drop_column("tenants", "setup_template_used")
    op.drop_column("tenants", "purge_scheduled_at")
    op.drop_column("tenants", "offboarding_started_at")

    op.drop_constraint("ck_classes_stream", "classes", type_="check")
    op.drop_index("ix_classes_stream", table_name="classes")
    op.drop_column("classes", "stream")

    op.drop_column("school_units", "gr_number_scheme")
